- name: Install transmission
  ansible.builtin.apt:
    package:
      - transmission-daemon
- name: Enable transmission
  ansible.builtin.service:
    name: transmission-daemon
    state: stopped
    enabled: true
- name: Write transmission configuration
  ansible.builtin.copy:
    src: etc/transmission-daemon/settings.json
    dest: /etc/transmission-daemon
    owner: debian-transmission
    group: debian-transmission
    mode: "0644"
- name: Start transmission
  ansible.builtin.service:
    name: transmission-daemon
    state: started
